config/routes.rb
Rails.application.routes.draw do

  root to: redirect('/maker/index')
  get 'maker', to: redirect('/maker/index')
  scope :maker do
    match 'index' => 'maker#index', :via => :all, :as => :maker_index
    scope :user do
      match :student, :to => 'student#index', :via => [:post, :get], as: :maker_user_student
      resources :canteen_worker, only: [:index], as: :maker_user_canteen_worker
      match 'admin', :to => 'admin#index', :via => [:post, :get], :as => :maker_user_admin
      match 'login', :to => 'user#login', :via => [:post, :get], :as => :maker_user_login
      match 'register', :to => 'user#register', :via => [:get, :post], :as => :maker_user_register
      match 'logout', :to => 'user#logout', :via => :get, :as => :maker_user_logout
      match 'password_reset', :to => 'user#password_reset', :via => [:get, :post], :as => :maker_user_password_reset
    end
    match '*unmatched_route', :to => 'application#invalid_page', :via => :all
  end

end

app/controllers/user_controller.rb
require_relative '../../app/helpers/application_helper'
include ApplicationHelper

class UserController < ApplicationController
  def permitted_params
    params.permit!
  end
  def login
    @operate_type = '用户登陆'
    respond_to do |format|
      if request.request_method =~ /post/i
        account = params[:account]
        password = params[:password]

        if account.blank? && password.blank?
          append_msg(:danger, '用户名和密码不能为空')
        elsif account.blank?
          append_msg(:danger, '用户名不能为空')
        elsif password.blank?
          append_msg(:danger, '密码不能为空')
        else
          student = Student.find_by_account(account)
          @user = nil
          @user_type = nil
          if student
            student = Student.find_by_password(password)
            if student
              @user = student
              @user_type = USER_TYPE[:student]
            else
              append_msg(:danger, '密码填写不正确')
            end
          else
            canteen_worker = CanteenWorker.find_by_account(account)
            if canteen_worker
              canteen_worker = CanteenWorker.find_by_password(password)
              if canteen_worker
                @user = canteen_worker
                grant = canteen_worker.granted
                if grant.table_name == 'all'
                  @user_type = USER_TYPE[:admin]
                else
                  @user_type = USER_TYPE[:canteen_worker]
                end
              else
                append_msg(:danger, '密码填写不正确')
              end
            else
              append_msg(:danger, '用户名填写不正确')
            end
          end
        end
      end

      if @user
        session_set(@user, @user_type)
      end
      format.js {render partial: 'user/login.js.erb', :layout => false}
    end
  end

  def register
    permitted_params
    @operate_type = '用户注册'
    if request.request_method =~ /post/i
      if params[:activate]# 激活 post
        password = params[:password]
        confirm_password = params[:confirm_password]
        if password.blank? && confirm_password.blank?
          append_msg(:danger, '未填写密码')
        else
          if password == confirm_password
            @student = Student.find_by_email(params[:email])
            if @student.update({ password: password, account: params[:email]})
              @user = @student
              @user_type = USER_TYPE[:student]
              session_set(@user, @user_type)#设置session
            else
              append_errors_msg(@student)
            end
          else
            append_msg(:danger, '密码和确认密码不匹配')
          end
        end
        respond_to do |format|
          format.js {render partial: 'user/activation.js.erb', :layout => false}
        end
      else #请求邮箱注册
        begin
          @student = Student.create!(params[:student])
          @student.activation
          # append_msg(:success, '邮件发送成功')
          respond_to do |format|
            format.js {render partial: 'user/send_email_success.js.erb', :layout => false}
          end
        rescue => e
          append_errors_msg(e.record)
          respond_to do |format|
            format.js {render partial: 'template/message_notice.js.erb', :layout => false}
          end
        end
      end
    else
      if params[:email]#账号激活
        @student = Student.find_by(email: params[:email], activation_token: params[:activation_token])
        if @student && Time.new < @student.updated_at + 1.hour #注册时这里通过updated_at属性来判断链接是否有效
          if @student.account
            invalid_page #已经激活,页面失效,避免二次激活
          else
            render 'user/activation.html.erb'
          end
        else
          if @student
            @student.delete
          end
          invalid_page
        end
      else
        @student = Student.new
        respond_to do |format|
          format.js {render partial: 'user/get_register_page.js.erb', :layout => false}
        end
      end
    end
  end

  def password_reset
    @operate_type = '密码重置'
    respond_to do |format|
      if request.request_method =~ /post/i

      else

      end
    end
  end

  def activation
    render 'user/activation.html.erb'
  end

  def logout
    session_delete
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/user/_activation.js.erb
<% if flush_length == 0 %>
<% if params[:goto]#跳转至完善个人信息 %>
window.location.href = '<%= maker_user_student_path %>'
<% else %>
window.location.href = '<%= maker_path %>'
<% end %>
<%else %>
page_notice('<%= escape_javascript(render :partial => 'template/bs_alert.html.erb')%>');
<% end%>

app/views/user/_get_register_page.js.erb
$("<%= escape_javascript(render :partial => 'user/register.html.erb', layout: 'layouts/edit_modal.html')%>").modal()
        .find('.modal-dialog').addClass('modal-dialog-460');

app/views/user/_login.html.erb
  <%= form_tag(maker_user_login_path, remote: true, method: :post) do %>
      <div class="form-group">
        <%= label_tag(:account, '账号') %>
        <%= text_field_tag(:account, '', class: 'form-control', placeholder: '请输入账号') %>
      </div>
      <div class="form-group">
        <%= label_tag(:password, '密码') %>
        <%= password_field_tag(:password, '', class: 'form-control', placeholder: '请输入密码', autocomplete: 'off') %>
      </div>
      <!-- //用于阻止 chrome表单自动填充的占位符 -->
      <input class='hidden' type="text" />
      <input class='hidden' type="password"/>
      <!-- //用于阻止 chrome表单自动填充的占位符 -->
      <!--<div class="form-group col-sm-6">-->
        <!--<button type="submit" class="btn-lg btn-primary btn-block">注册</button>-->
      <!--</div>-->
      <div class="form-group">
        <button type="submit" class="btn btn-primary btn-block">登陆</button>
      </div>
      <div class="form-group">
        <div class="text-info text-center">提示:工作人员使用工号登陆，非工作人员请使用国科大邮箱登陆</div>
      </div>
  <% end %>

app/views/user/_login.js.erb
<% if request.request_method =~ /get/i %>
    $("<%= escape_javascript(render :partial => 'user/login.html.erb', layout: 'layouts/edit_modal.html')%>")
    .modal().find('.modal-dialog').addClass('modal-dialog-460');
<% else %>
    <% if flush_length > 0 %>
            page_notice('<%= escape_javascript(render :partial => 'template/bs_alert.html.erb')%>');
        <%
       else
        if @user_type == USER_TYPE[:student]
            %>
window.location.href = '<%= maker_user_student_path%>';
<%
        elsif @user_type == USER_TYPE[:admin]
            %>
        window.location.href = '<%= maker_user_admin_path%>';
    <%
        else
        end
       end
    %>
<% end %>

app/views/user/_register.html.erb
<%= form_for(@student, url: maker_user_register_path, remote: true, method: :post) do |f|%>
      <div class="alert alert-info alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <strong>注意:</strong>注册发送链接后将在一小时后失效
      </div>
    <div class="form-group">
      <%= f.label(:email, '国科大邮箱') %>
      <%= f.text_field(:email, class: 'form-control', placeholder: '请输入国科大邮箱') %>
    </div>
    <div class="form-group">
      <div class="checkbox text-danger">
        <label>
          <%= check_box_tag(:goto, :goto, true) %>
          邮件发送成功自动跳转到国科大邮箱主页
        </label>
      </div>
    </div>
    <div class="form-group">
      <button type="submit" class="btn btn-primary btn-block" id="send-email">发送邮件注册</button>
    </div>
    <div class="form-group">

    </div>
    <div class="form-group">
      <div class="text-info">提示:只能使用国科大邮箱注册</div>
    </div>
<% end %>

app/views/user/_send_email_success.js.erb
<% if params[:goto].blank? %>
var send_email = $("#send-email");
send_email.parent().next().hide().fadeIn('slow', function () {
    $(this).html('<%= link_to '邮件已经发送成功,请点击去激活', UCAS_MAIL_ADDRESS, class: 'btn btn-success btn-block' %>')
    send_email.html('重新发送');
});

<% else%>
window.location.href = '<%= UCAS_MAIL_ADDRESS %>';
<%end %>

app/views/user/activation.html.erb
<% provide(:title, '账号激活') %>
<div class="container">
  <div class="jumbotron" style="padding-top: 0px">
    <div class="container">
      <h2 class="text-center"><%= WEB_NAME %>欢迎新用户激活</h2>
      <hr/>
      <div class="row">
        <div class="col-sm-2"></div>
        <div class="col-sm-8">
          <%= form_for(@student, url: maker_user_register_path, remote: true, method: :post) do |f|%>
              <%= hidden_field_tag(:activate, 'activate') %>
              <%= hidden_field_tag(:email, @student.email) %>
              <div class="form-group">
                <div class="alert alert-success" role="alert">
                  登陆账号: <strong><%= @student.email %></strong>
                </div>
              </div>
              <div class="form-group">
                <%= label_tag(:password, '密码') %>
                <%= password_field_tag(:password, '', class: 'form-control', autocomplete: 'off') %>
              </div>
              <div class="form-group">
                <%= label_tag(:confirm_password, '确认密码') %>
                <%= password_field_tag(:confirm_password, '', class: 'form-control') %>
              </div>
              <!-- //用于阻止 chrome表单自动填充的占位符 -->
              <input class='hidden' type="text" />
              <input class='hidden' type="password"/>
              <!-- //用于阻止 chrome表单自动填充的占位符 -->
              <div class="form-group">
                <div class="checkbox text-danger">
                  <label>
                    <%= check_box_tag(:goto, :goto, true) %>
                    勾选表示激活后自动登陆跳转至完善个人信息,否则自动登陆跳转至首页
                  </label>
                </div>
              </div>
              <div class="form-group">
                <button type="submit" class="btn btn-primary btn-block" id="send-email">确定</button>
              </div>
              <div class="form-group">

              </div>
              <div class="form-group">
                <div class="text-danger">
                  <strong>注意:</strong>
                  <div>密码长度必须6到16位,而且必须是数字和字母组合</div>
                  <div>激活成功后页面将失效</div>
                </div>
              </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>